default['atheme-services']['config']['nickserv']['enable'] = true

# TODO
# default['atheme-services']['config']['nickserv']['access'] = {}
default['atheme-services']['config']['nickserv']['aliases'] = {
    "ID" => "IDENTIFY",
    "MYACCESS" => "LISTCHANS"
}
default['atheme-services']['config']['nickserv']['host'] = "services.int"
default['atheme-services']['config']['nickserv']['maxnicks'] = 5
default['atheme-services']['config']['nickserv']['nick'] = "NickServ"
default['atheme-services']['config']['nickserv']['no_nick_ownership'] = false
default['atheme-services']['config']['nickserv']['real'] = "Nickname Services"
default['atheme-services']['config']['nickserv']['spam'] = true
default['atheme-services']['config']['nickserv']['user'] = "NickServ"

default['atheme-services']['config']['nickserv']['modules']['access'] = false
default['atheme-services']['config']['nickserv']['modules']['badmail'] = true
default['atheme-services']['config']['nickserv']['modules']['cert'] = false
default['atheme-services']['config']['nickserv']['modules']['cracklib'] = false
default['atheme-services']['config']['nickserv']['modules']['drop'] = true
default['atheme-services']['config']['nickserv']['modules']['enforce'] = false
default['atheme-services']['config']['nickserv']['modules']['ghost'] = true
default['atheme-services']['config']['nickserv']['modules']['group'] = true
default['atheme-services']['config']['nickserv']['modules']['help'] = true
default['atheme-services']['config']['nickserv']['modules']['hold'] = true
default['atheme-services']['config']['nickserv']['modules']['identify'] = true
default['atheme-services']['config']['nickserv']['modules']['info'] = true
default['atheme-services']['config']['nickserv']['modules']['info_lastquit'] = false
default['atheme-services']['config']['nickserv']['modules']['list'] = true
default['atheme-services']['config']['nickserv']['modules']['listmail'] = true
default['atheme-services']['config']['nickserv']['modules']['listownmail'] = false
default['atheme-services']['config']['nickserv']['modules']['login'] = false
default['atheme-services']['config']['nickserv']['modules']['logout'] = true
default['atheme-services']['config']['nickserv']['modules']['mark'] = true
default['atheme-services']['config']['nickserv']['modules']['freeze'] = true
default['atheme-services']['config']['nickserv']['modules']['listchans'] = true
default['atheme-services']['config']['nickserv']['modules']['listgroups'] = true
default['atheme-services']['config']['nickserv']['modules']['register'] = true
default['atheme-services']['config']['nickserv']['modules']['regnolimit'] = true
default['atheme-services']['config']['nickserv']['modules']['resetpass'] = true
default['atheme-services']['config']['nickserv']['modules']['restrict'] = true
default['atheme-services']['config']['nickserv']['modules']['return'] = true
default['atheme-services']['config']['nickserv']['modules']['setpass'] = true
default['atheme-services']['config']['nickserv']['modules']['sendpass'] = false
default['atheme-services']['config']['nickserv']['modules']['sendpass_user'] = true
default['atheme-services']['config']['nickserv']['modules']['set_core'] = true
default['atheme-services']['config']['nickserv']['modules']['set_accountname'] = true
default['atheme-services']['config']['nickserv']['modules']['set_email'] = true
default['atheme-services']['config']['nickserv']['modules']['set_emailmemos'] = true
default['atheme-services']['config']['nickserv']['modules']['set_enforcetime'] = false
default['atheme-services']['config']['nickserv']['modules']['set_hidemail'] = true
default['atheme-services']['config']['nickserv']['modules']['set_language'] = true
default['atheme-services']['config']['nickserv']['modules']['set_nevergroup'] = true
default['atheme-services']['config']['nickserv']['modules']['set_neverop'] = true
default['atheme-services']['config']['nickserv']['modules']['set_nogreet'] = true
default['atheme-services']['config']['nickserv']['modules']['set_nomemo'] = true
default['atheme-services']['config']['nickserv']['modules']['set_noop'] = true
default['atheme-services']['config']['nickserv']['modules']['set_password'] = true
default['atheme-services']['config']['nickserv']['modules']['set_privmsg'] = false
default['atheme-services']['config']['nickserv']['modules']['set_private'] = false
default['atheme-services']['config']['nickserv']['modules']['set_property'] = true
default['atheme-services']['config']['nickserv']['modules']['set_quietchg'] = true
default['atheme-services']['config']['nickserv']['modules']['status'] = true
default['atheme-services']['config']['nickserv']['modules']['taxonomy'] = true
default['atheme-services']['config']['nickserv']['modules']['vacation'] = true
default['atheme-services']['config']['nickserv']['modules']['verify'] = true
default['atheme-services']['config']['nickserv']['modules']['vhost'] = true
